### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by gavanmcgrath** [hydrogeoscience/pygtide#13]
Hi is there any reason why this does not run on anaconda 3 python 3.7.
I downloaded pygtide and ran the following:

import os
os.chdir("C:\\Users\\Downloads\\pygtide-master\\pygtide-master")
import pygtide

to get the following:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c3c1fb791fa3> in <module>
      3 import os
      4 os.chdir("C:\\Users\\Downloads\\pygtide-master\\pygtide-master")
----> 5 import pygtide

~\Downloads\pygtide-master\pygtide-master\pygtide\__init__.py in <module>
----> 1 from .pygtide import pygtide

~\Downloads\pygtide-master\pygtide-master\pygtide\pygtide.py in <module>
     94 import pandas as pd
     95 import datetime as dt
---> 96 from etpred import etpred
     97 import os
     98 from sys import path

~\Downloads\pygtide-master\pygtide-master\etpred\__init__.py in <module>
----> 1 from . import etpred

ImportError: DLL load failed: The specified module could not be found.

**Comment by hydrogeoscience** [comment]
Please see the new update.
