### ISSUE TITLE
no module named etpred

### ISSUE THREAD

**Issue by Udmmi** [hydrogeoscience/pygtide#21]
Hey
Maybe this is a problem for me because I'm a noobie. But when I try to run the program I get this error:  
 File ~\.spyder-py3\pygtide-master\pygtide.py:97 in <module>
    import etpred

ModuleNotFoundError: No module named 'etpred'

From what I understood, this module is in the other files, but when I try to run it, it doesn't recognize it. Any idea on how to solve this?

**Comment by hydrogeoscience** [comment]
Please make sure you use one of the Python versions that is mentioned

**Comment by hydrogeoscience** [comment]
Please try our new version v0.6
