### ISSUE TITLE
Calculating solid tides before 1962

### ISSUE THREAD

**Issue by glPeng-seis** [hydrogeoscience/pygtide#23]
I found that we can not update the data in the file etpolut1.dat before 1962. we thus can not calculate the tides before 1962. How to solve this problem. Thanks for your help.

**Comment by hydrogeoscience** [comment]
This may be an overall limitation of ETERNA. I will look into this when I have some time. Before doing so, can you tell me where you get pole position data from before the year 1962?

**Comment by hydrogeoscience** [comment]
Does it not work for times before 1962 right now?

**Comment by GPeng00** [comment]
Yes, it do not work. The traceback as following,

Traceback (most recent call last):
  File "run_calc_tide.py", line 62, in <module>
    ranking = calc_volume_strain_indays(date_onset, nterms, samp, vol_nm, la, lo, elev)
  File "/mnt/j/Vols/calc_tide.py", line 65, in calc_volume_strain_indays
    pt.predict(lat, lon, height, start, duration, splrate, tidalcompo=8)
  File "/mnt/j/Vols/pygtide/pygtide.py", line 368, in predict
    "Please update file '%s'." % (self.etpolut1_start, self.etpolut1_end, file))
**ValueError:** Dates exceed permissible range for pole/LOD tide correction (interval 1962-01-01 00:00:00 to 2023-06-10 00:00:00). Please update file 'etpolut1.dat'.

**Comment by hydrogeoscience** [comment]
Thanks. I have updated core.py and changed the error to a user warning. This should now work for years before 1962.
