### ISSUE TITLE
ModuleNotFoundError: No module named 'pygtide.etpred'

### ISSUE THREAD

**Issue by GPeng00** [hydrogeoscience/pygtide#25]
Hi Gabriel. After installation by 'pip install pygtide' in Ubuntu 20.04.  I tested pygtide then prompted error message.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/j/Vols/pygtide/pygtide/__init__.py", line 5, in <module>
    from pygtide.update_etpred_data import update
  File "/mnt/j/Vols/pygtide/pygtide/update_etpred_data.py", line 7, in <module>
    import pygtide.etpred as etpred
ModuleNotFoundError: No module named 'pygtide.etpred'

**Comment by trichter** [comment]
Hi @GPeng00, any errors when installing? Maybe a Fortran compiler is missing? In conda you can install it with `conda install fortran-compiler`.

**Comment by GPeng00** [comment]
Hi @trichter. It should not be an installation problem, because there is no any problem installing and using last version of pygtide.

**Comment by trichter** [comment]
For me the installation is working on ubuntu. `etpred` hosts the compiled Fortran code.  I'd guess that something went wrong with the compilation.

**Comment by GPeng00** [comment]
i reinstalled the pygtide. The steps are as follows，
conda create -n pygtide python=3.7
conda install numpy pandas requests git
conda install fortran-compiler
pip install pygtide 

This process did not prompt any error messages.
When testing 'import pygtide', the error messages are as follows，
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/f/pygtide0.7/pygtide/__init__.py", line 1, in <module>
    from pygtide.core import pygtide
  File "/mnt/f/pygtide0.7/pygtide/core.py", line 93, in <module>
    import pygtide.etpred as etpred
ModuleNotFoundError: No module named 'pygtide.etpred'

I think that it maybe absence of etpred module. In current version，the content of pygtide contains folder commdat and files __init__.py,  core.py, tests.py and update_etpred_data.py. In core.py, require 'import pygtide.etpred as etpred', but etpred is disappearance.

**Comment by trichter** [comment]
Interesting. This is working for me:

```
conda create -n test2pygtide python=3.7 numpy pandas fortran-compiler
conda activate test2pygtide
pip install pygtide
python -c 'import pygtide; pygtide.test()'
```

etpred is the compiled Fortran module created during the installation process. Did you activate the environment? Are you in the folder with the downloaded source code when trying to import? If yes, please change to another folder.

**Comment by GPeng00** [comment]
Indeed，it is working in the pygtide folder. Thank you for your help.

**Comment by GPeng00** [comment]
Indeed，it is working in the pygtide folder. Thank you for your help.

**Comment by GPeng00** [comment]
It is inconvenient, working content is required  in pygtide folder. A better approach is that we can call pygtide in any content.
