### ISSUE TITLE
LOD tide is unsteady

### ISSUE THREAD

**Issue by hydrogeoscience** [hydrogeoscience/pygtide#27]
The LOD tide shows unsteadiness. This results from the code interpolating data from etpolut1.dat and then differentiating it.
Is there a solution that makes the results steady?

**Comment by trichter** [comment]
Can you provide the code snippet with which you generated the LOD and pole tidal contribution?

**Comment by trichter** [comment]
@hydrogeoscience I can work on this issue.

**Comment by hydrogeoscience** [comment]
This is done in lines 2976-2999 in Fortran
