### ISSUE TITLE
Availability of the modified ETERNA PREDICT Fortran source code

### ISSUE THREAD

**Issue by jnsebgosselin** [hydrogeoscience/pygtide#3]
I'm interested in using `pygtide` in one of my projects. Thanks for this work, this seems very promising.

Would it be possible to push the modified ETERNA PREDICT Fortran source code on the project repository so that it would be possible to build the `etpred` Python extension for Python 3.7 and using the 64-bit compilers from `Mingw-64`?

Also, I can provide some help, if needed, for the creation of a `setup.py` file, so that the extension can be built more easily on different Python environments and platforms. I can also help with the creation of pip wheels and conda packages to make the package even easier to install.

**Comment by jnsebgosselin** [comment]
I just saw that PR #2 is a good step forward to provide support for more environments and platforms and making the package easier to use and to install.

If possible, I still think that would be a good idea to provide the modified Fortran source code on this repo.

**Comment by trichter** [comment]
I am also interested in pygtide. I tried the linux extensions from #2 and it's promising. Only, it's difficult to see at which place the fortran code errors without the modified source code. I also think it would be a great idea to provide your modified source files again, so that others can build upon your work. Another option would be to provide only the diff to the original source file which can be separately downloaded.

**Comment by ioshchepkov** [comment]
Thanks for your work on this important project! I also support the idea of publishing the Fortran source code and to have an ability to compile the whole thing from scratch (i.e. from `setup.py`).
If I understand correctly, the original ETERNA is not free, despite the fact that it is on the Internet. As suggested by @trichter, from the legal point of view, it is better to use diff file. However, from the user's point of view, the full source file is much better.

**Comment by hydrogeoscience** [comment]
Unfortunately, I am not able to upload the source code because I do not own the copyright.

**Comment by jnsebgosselin** [comment]
You don't need to own the copyright to share the source code, it all depends under which license this source code is distributed. But of course, if you had the copyrights, this would be a non issue...

If the license is very restrictive, you might not even have the rights to share the binaries (.pyd and .so) that you are compiling from your modified version of the code.

On the website where the code is freely available, there is no mention of the license under which the code is distributed... I'm not an expert on this subject, so take that with a grain of salt, but I think that when this is the case, all rights are reserved to the owner of the copyrights and even compiled binaries of the code cannot be freely distributed without the consent of the copyrights owner.

**Comment by jnsebgosselin** [comment]
There is also a new package that is being developed which is a port of ETERNA to C++ and R. It is distributed under the GNU-GPL license (https://github.com/jkennel/earthtide). I wonder if they obtained the consent of the owner of the code to do that...

**Comment by hydrogeoscience** [comment]
I am aware of all that. I am in close contact with Dr Forbriger from BFO who is a colleague of the late Prof Wenzel. He mentioned that there are copyright issues which need sorting out, so I am going to wait until this is sorted.

**Comment by hydrogeoscience** [comment]
Thanks, I saw that. Everyone basically pulls the Fortran from IGETS. As I mentioned, there are copyright issues that need resolving.

**Comment by jnsebgosselin** [comment]
> I am aware of all that. I am in close contact with Dr Forbriger from BFO who is a colleague of the late Prof Wenzel. He mentioned that there are copyright issues which need sorting out, so I am going to wait until this is sorted.

OK, I understand. These copyright issues are a pain to deal with... If you are authorized to distribute the binaries, that is all good.
