### ISSUE TITLE
update etddt.dat

### ISSUE THREAD

**Issue by WilkAndy** [hydrogeoscience/pygtide#6]
I get this warning:
```
Prediction timeframe exceeds the end of the available time database (2017-01-01 00:00:00) plus 1 year. For best accuracy, please consider updating 'etddt.dat'
```
I attempted to update etddt.dat but the newly-downloaded file appeared to be the same as the one in the repo, so i must have done something wrong.
Perhaps the version in the repo could be updated?

**Comment by Jollyfant** [comment]
Should be this file: http://igets.u-strasbg.fr/Documents/etddt.dat

**Comment by Jollyfant** [comment]
PR #10

**Comment by hydrogeoscience** [comment]
Please see the new update.
