### ISSUE TITLE
etpolut1_end problem

### ISSUE THREAD

**Issue by WilkAndy** [hydrogeoscience/pygtide#8]
Could be related to #7 .
To get pygtide to run, i must change this line
```
        self.etpolut1_end = dt.datetime.strptime(str(etpred.inout.etpol_end), "%Y%m%d")
```
to hardcode the end date.  Eg
```
self.etpolut1_end = dt.datetime.strptime(str(20190821), \"%Y%m%d\")
```
This is because `str(etpred.inout.etpol_end) = '0'`

**Comment by hydrogeoscience** [comment]
Please see the new update.
