### ISSUE TITLE
gaurantee test output is correct

### ISSUE THREAD

**Issue by WilkAndy** [hydrogeoscience/pygtide#9]
When i run test.py i get some output.  Yippee :-)   But how do i know it's correct?  I suggest including an "expected_output" file.

**Comment by cdbag** [comment]
I also have the same curiosity. Did you able to check it? Also, in the manual it says that the output shows a plot of data but I just get some listed results not a plot.

**Comment by WilkAndy** [comment]
No, i'm just assuming my version is correct.   You probably have to manually plot the data

**Comment by hydrogeoscience** [comment]
Please see the new update.
